### ISSUE TITLE
Install Scope with AWS not including latest version of Scope

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/integrations#119]
I ran the AWS cloudformation from these instructions: 

https://www.weave.works/docs/scope/latest/installing/#ecs

and what I'm seeing is Scope 1.1 and  also an old version of Net. 

I am expecting to see 1.2.  

I think something has regressed.

**Comment by 2opremio** [comment]
The default value of the scope version in the templates hasn't yet been
updated. It's not a regression.

The integrations repository and scope follow different release paces.

You can however use a non-default value for the version being deployed,
there is a parameter for that.

On Feb 16, 2017 21:22, "Anita Buehrle" <notifications@github.com> wrote:

I ran the AWS cloudformation from these instructions:

https://www.weave.works/docs/scope/latest/installing/#ecs

and what I'm seeing is Scope 1.1. I think something has regressed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/weaveworks/integrations/issues/119>, or mute the thread

**Comment by abuehrle** [comment]
I tried both 1.2.0 or 1.2 for Weave Scope . 

and also 1.9.0 and 1.9 for Weave Net. 

Unfortunately that doesn't work either -- still loads the prior versions. 

![screen shot 2017-02-16 at 2 24 29 pm](https://cloud.githubusercontent.com/assets/13420383/23044412/b39f595c-f465-11e6-9a1f-d905c0393d48.png)

**Comment by 2opremio** [comment]
Can you please create a separate ticket for this? (Cc @errordeveloper )
