### ISSUE TITLE
Selective disabling Scope/Weave Net

### ISSUE THREAD

**Issue by peterdeka** [weaveworks/integrations#95]
As there are filed (weaveworks/guides#181) Scope CPU and instability issues with bursting EC2 instances (and the problem gets worse as the number of involved container instances increases), it would be crucial to be able to use only Weave Net in order to preserve the functionality even on crap instances.

**Comment by 2opremio** [comment]
As a workaround, you can disable Weave Scope by adding the following

```
rm /etc/init/scope.conf
```

To your instances [User Data](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-shell-scripts)

**Comment by peterdeka** [comment]
At the moment i can confirm that disabling scope solves the issue (obviously depends on your proprietary containers workload). 

![with scope](https://cloud.githubusercontent.com/assets/1216864/16157751/43ba0b2a-34ba-11e6-96c6-f8c307d3d09c.png)
with scope

![without scope](https://cloud.githubusercontent.com/assets/1216864/16157750/43b6d8a6-34ba-11e6-9a7e-605d5c1340fa.png)
without scope

**Comment by 2opremio** [comment]
I've been giving some thought to this and:
1. We can't disable Weave Net since Scope depends on Net for service discovery when instances go up and down.
2. The workaround from https://github.com/weaveworks/integrations/issues/95#issuecomment-226729307 is better than adding an extra configuration variable since Upstart would expect a process to be running.

So, I am going to document doing `echo manual > /etc/init/scope.conf` from the User Data as suggested in http://askubuntu.com/questions/19320/how-to-enable-or-disable-services
